services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080
    networks:
      - dokploy-network
    deploy:
      replicas: 3
    environment:
      - PORT=8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.citest.rule=Host(`ci.tukashi.com`)"
      - "traefik.http.routers.citest.entrypoints=websecure"
networks:
  dokploy-network:
    name: dokploy-network
    external: true